version: '3.8'
services:
  db:
    image: postgres
    restart: always
    container_name: postgresdb-template
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123321
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
